title: Joshua Nghe
logo: /assets/profile.png
description: Welcome to my portfolio! I'm a junior level student, a programmer, and an aspiring data scientist. I enjoy utilizing statistical techniques to reveal narratives in data and generate predictive models for future insight.
show_downloads: true
theme: jekyll-theme-minimal
