title: Joshua Nghe
logo: /assets/profile.png
description: Welcome to my portfolio! I'm a junior level applied math student, and an aspiring data scientist. I enjoy utilizing statistical techniques to reveal narratives in data and create predictive models for future insights.
show_downloads: true
theme: jekyll-theme-minimal
