title: Joshua Nghe
logo: /assets/profile.png
description: Welcome to my website! I'm a junior level student, and I am a Data Analyst who specializes in applying advanced statistical techniques to uncover insights in sustainability trends and develop predictive models for environmental and economic insight.
show_downloads: true
theme: jekyll-theme-minimal
